package pit;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.jms.*;
import javax.naming.*;

/*
 * This is the ONLY file that you are to edit.  It is the model of play for
 * every PITplayer.  Each PITplayer instantiates this model and uses it to
 * process the messages it receives.
 */
public class PITPlayerModel {

    // Each PITplayer has a unique myPlayerNumber.  It is set in the PITPlayer constructor.
    private int myPlayerNumber;
    // Cards is this player's set of cards.  
    private final ArrayList<String> cards = new ArrayList<>();
    // numTrades counts trades.
    private int numTrades = 0;
    // maxTrades is the maximum number of trades, after which trading is stopped.
    private final int maxTrades = 20000;
    // numPlayers are the number of Players trading.  This comes with a NewHand from the PITsnapshot servlet
    private int numPlayers = 0;
    
    

    /* The snapshot servlet (PITsnapshot) is expecting to be passed an ObjectMessage
     * where the object is a HashMap. Therefore this definition of that HashMap is 
     * provided although it is not currently used (it is for you to use).
     * PITsnapshot is expecting a set of attibute/value pairs.  These include the player
     * number, as in state.put("Player", myPlayerNumber), and each commodity string
     * and the number of that commodity in the snapshot.
     * Also included below is a utility method that will turn a HashMap into a string
     * which is useful for printing diagnostic messages to the console.
     */
    
    private HashMap<String, Integer> state;
    
    private boolean isPlaying;
    private ArrayList<Integer>blocked;
    private ArrayList<Integer>markerFromOthers;
    

    // PITPlayerModel constructor saves what number player this object represents.
    PITPlayerModel(int myNumber) {
        myPlayerNumber = myNumber;
        state = new HashMap<>();
        isPlaying = false;
        blocked = new ArrayList<>();
        markerFromOthers = new ArrayList<>();       
    }

    public void onMessage(Message message) {
        try {
            if (message instanceof ObjectMessage) {
                Object o = ((ObjectMessage) message).getObject();

                // There are 4 types of messages:  Reset, NewHand, Trade, and Marker
                // Reset the Player.  The Reset message is generated by the PITsnapshot servlet
                if (o instanceof Reset) {
                    doReset((Reset) o);

                // NewHand received from PITsnapshot
                } else if (o instanceof NewHand) {
                    // Add the new hand into cards
                    doNewHand((NewHand) o);

                // Receive a Trade from another Player
                } else if (o instanceof Trade) {
                    // Add the trade into cards
                    doReceiveTrade((Trade) o);

                } else if (o instanceof  Marker) {
                    doReceiveMarker((Marker)o);
                    doMakeTrade();
                } else {
                    System.out.println("PITplayer" + myPlayerNumber + " received unknown Message type");
                    // just ignore it
                }
            }
        } catch (Exception e) {
            System.out.println("Exception thrown in PITplayer" + myPlayerNumber + ": " + e);
        }
    }

    private void doReset(Reset reset) throws Exception {
        System.out.println("PITplayer" + myPlayerNumber + " received reset");
        // Drop all cards in hand
        cards.clear();
        numTrades = 0;
        numPlayers = 0;
        // Reply to the PITsnapshot servlet acknowledging the Reset
        resetStates();
        sendToQueue("jms/PITmonitor", reset);
    }

    private void doNewHand(NewHand hand) throws Exception {
        // Add new hand cards.  
        // It is actually possible that a trade had added a card already.
        resetStates();
        cards.addAll((hand).newHand);
        numPlayers = (hand).numPlayers;
        System.out.println("PITplayer" + myPlayerNumber + " new hand: " + toString(cards));
        // Trade away a card
        doMakeTrade();
    }
    
    private void doReceiveTrade(Trade trade) throws Exception {
        // Having received a Trade card from another Player, add it to my hand of cards
        cards.add(trade.tradeCard);

        System.out.println("PITplayer" + myPlayerNumber + " received: " + trade.tradeCard + " from player: " + trade.sourcePlayer);
        System.out.println("PITplayer" + myPlayerNumber + " hand: " + toString(cards));
        // Trade away a card
        if (isPlaying && 
                !blocked.contains(trade.sourcePlayer)) {
            if(state.containsKey(trade.tradeCard)) {
                int count = state.get(trade.tradeCard);
                count ++;
                state.put(trade.tradeCard, count);
             }else {
                state.put(trade.tradeCard, 1);
            }
        }
        
        doMakeTrade();
    }
    
    private void doMakeTrade() throws Exception {

        // if hit maxTrades limit, then stop sending trades
        if (maxTrades(maxTrades)) {
            return;
        }

        /*
         * If numPlayers == 0, while we have received a Trade, we have not 
         * received our NewHand yet, so we don't know how many players there 
         * are.  Therefore, don't send out a Trade at this time.
         * 
         */
        if (numPlayers == 0) {
            return;
        }

        // Create a new Trade from my set of cards, and send to another player
        Trade newTrade = new Trade();
        newTrade.tradeCard = (String) cards.remove(0);
        newTrade.sourcePlayer = myPlayerNumber;

        // Find a random player to trade to (not including myself)
        int sendTo = myPlayerNumber;
        while (sendTo == myPlayerNumber) {
            sendTo = Math.round((float) Math.random() * (numPlayers - 1));
        }

        //Send the card to the other player
        System.out.println("PITplayer" + myPlayerNumber + " sending: " + newTrade.tradeCard + " to player: " + sendTo);
        String sendToJNDI = "jms/PITplayer" + sendTo;
        sendToQueue(sendToJNDI, newTrade);

    }

    // Create a string of hand size and all cards for use in printing
    private String toString(ArrayList hand) {

        String cardsString = "size: " + hand.size() + " ";
        for (int i = 0; i < hand.size(); i++) {
            cardsString += hand.get(i) + " ";
        }
        return cardsString;
    }

    // Create a printable version of the "state".
    private String toString(HashMap<String, Integer> state) {
        String stateString = "";
        for (Iterator it = state.entrySet().iterator(); it.hasNext();) {
            Map.Entry entry = (Map.Entry) it.next();
            String commodity = (String) entry.getKey();
            int number = ((Integer) entry.getValue()).intValue();
            stateString += "{" + commodity + ":" + number + "} ";
        }
        return stateString;
    }

    // Send an object to a Queue, given its JNDI name
    private void sendToQueue(String queueJNDI, Serializable message) throws Exception {
        // Gather necessary JMS resources
        Context ctxt = new InitialContext();
        Connection con = ((ConnectionFactory) ctxt.lookup("jms/myConnectionFactory")).createConnection();
        Session session = con.createSession(false, Session.AUTO_ACKNOWLEDGE);
        Queue q = (Queue) ctxt.lookup(queueJNDI);
        MessageProducer writer = session.createProducer(q);
        ObjectMessage msg = session.createObjectMessage(message);
        // Send the object to the Queue
        writer.send(msg);
        session.close();
        con.close();
        ctxt.close();
    }

    // Stop trading when the max number of Trades is reached
    private boolean maxTrades(int max) {
        if ((numTrades % 100) == 0) {
            System.out.println("PITplayer" + myPlayerNumber + " tradeCount: " + numTrades);
        }
        return (numTrades++ < max) ? false : true;
    }

    private void doReceiveMarker(Marker marker) throws Exception {
        if (marker.source != -1) {
            markerFromOthers.add(marker.source);
            blocked.add(marker.source);
        }
        
        if(!isPlaying) {
            isPlaying = true;
            state.put("Player",myPlayerNumber);
            for (String card : cards) {
                if(state.containsKey(card)) {
                    int count  = state.get(card);
                    count ++;
                    state.put(card, count);
                }else {
                    state.put(card, 1);
                }
            }
            
            for (int i = 0; i < 5; ++i) {
                if (i != myPlayerNumber) {
                        sendToQueue("jms/PITplayer"+i, new Marker(myPlayerNumber));
                 }
            }
        }else {
            
            if(blocked.size() == 4) {
                sendToQueue("jms/PITsnapshot",state);
                resetStates();
            }
        }
    }

    private void resetStates() throws Exception {
        markerFromOthers.clear();
        blocked.clear();
        isPlaying = false;
        state.clear();
    }
}